apiVersion: v2
name: simplek8s-controller
description: Node-management controller for SimpleK8s clusters (reboots, distro updates)
type: application
version: 0.3.0
appVersion: 0.3.0
icon: https://simplek8s.org
