package updatecore

// Unit tests for SHA-512-crypt (PLAN.md §3.15, M8 D5): expected
// outputs generated by an independent implementation
// (`openssl passwd -6`, glibc crypt) — never hand-written.

import (
	"strings"
	"testing"
)

func TestCryptSHA512Vectors(t *testing.T) {
	for _, tc := range []struct {
		password, salt, want string
	}{
		{"Hello world!", "saltstring", "$6$saltstring$svn8UoSVapNtMuq1ukKS4tPQd8iKwSMHWjl/O817G3uBnIFNjnQJuesI68u4OTLiBFdcbYEdFCoEOfaS35inz1"},
		{"password", "abcdefgh12345678", "$6$abcdefgh12345678$wqcwmecJP21fyIxuaeh.SXsEzfC3P6cPVIXOF7PgKp4kc8045b184wkloBFW1YZdt6DUW/RQ1LvVJt47Gon0v1"},
		{"x", "s", "$6$s$SBlV1TrR7m/.1RRLMAAvh/x6acOyBKfXVqXOixcaFNbUhqE84RFnq6y5mvfWTW8EA6yIr1RuWU8IRsKA/9jfE."},
		{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "longsalt123", "$6$longsalt123$ICcQCuBXDIbjMpqJrHwkTh2u9u0y58RCD2UcMNkm2KBKlVaY7ms5zMQMwGyuRgErOjX3n7eYriir/x/J8AzaU0"},
		{"p@$$w0rd!#%^&*()_+-=[]{}|;:,.<>?", "./0123456789ABCD", "$6$./0123456789ABCD$tk0vgM9F6Fdtd5jghehBU0Rw7kRhTqGLGqxz0vjOodghaVOQN26Glx0b/uki.pQegG2L7jJa/B6.t5/TpEpEn/"},
		{"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "testsalt", "$6$testsalt$s9Z0Ho4aF.3dFiW4TebWWnmdDrqsr5KPh9WGnrVn.xjAuyYAlTbkH.OQ7.8GNcqyhXa7hF7qWO5lFaJ7WYTKx0"},
	} {
		got, err := CryptSHA512(tc.password, tc.salt)
		if err != nil {
			t.Errorf("CryptSHA512(%q) error: %v", tc.password, err)
			continue
		}
		if got != tc.want {
			t.Errorf("CryptSHA512(%q) =\n%s\nwant\n%s", tc.password, got, tc.want)
		}
	}
}

func TestCryptSHA512SaltValidation(t *testing.T) {
	for _, salt := range []string{"", "12345678901234567", "has space", "uniçode", "under_score", "dollar$ign"} {
		if _, err := CryptSHA512("pw", salt); err == nil {
			t.Errorf("CryptSHA512 salt %q: want error", salt)
		}
	}
	if _, err := CryptSHA512("pw", "ok./09AZaz"); err != nil {
		t.Errorf("valid salt refused: %v", err)
	}
}

func TestCryptSHA512Shape(t *testing.T) {
	got, err := CryptSHA512("rootpassword", "abcd1234")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(got, "$6$abcd1234$") || len(got) != len("$6$abcd1234$")+86 {
		t.Fatalf("bad shape: %q", got)
	}
}
